spring:
  cloud:
    nacos:
      discovery:
        server-addr: 39.105.211.35:8848
        namespace: 235d7e0f-509e-47d7-aada-305ee44df41f
        register-enabled: false

dubbo:
  registry:
    group: yumeiqi-service:dev
  consumer:
    check: false