package com.yumeiqi.dao;

import com.yumeiqi.domain.YmqClientDao;
import com.yumeiqi.domain.YmqClientDaoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YmqClientDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_client
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    long countByExample(YmqClientDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_client
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int deleteByExample(YmqClientDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_client
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_client
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int insert(YmqClientDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_client
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int insertSelective(YmqClientDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_client
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    List<YmqClientDao> selectByExampleWithBLOBs(YmqClientDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_client
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    List<YmqClientDao> selectByExample(YmqClientDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_client
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    YmqClientDao selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_client
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") YmqClientDao record, @Param("example") YmqClientDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_client
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") YmqClientDao record, @Param("example") YmqClientDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_client
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByExample(@Param("record") YmqClientDao record, @Param("example") YmqClientDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_client
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByPrimaryKeySelective(YmqClientDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_client
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(YmqClientDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_client
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByPrimaryKey(YmqClientDao record);
}