package com.yumeiqi.dao;

import com.yumeiqi.domain.YmqEmployeeDao;
import com.yumeiqi.domain.YmqEmployeeDaoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YmqEmployeeDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_employee
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    long countByExample(YmqEmployeeDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_employee
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    int deleteByExample(YmqEmployeeDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_employee
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    int deleteByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_employee
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    int insert(YmqEmployeeDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_employee
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    int insertSelective(YmqEmployeeDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_employee
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    List<YmqEmployeeDao> selectByExampleWithBLOBs(YmqEmployeeDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_employee
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    List<YmqEmployeeDao> selectByExample(YmqEmployeeDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_employee
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    YmqEmployeeDao selectByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_employee
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") YmqEmployeeDao record, @Param("example") YmqEmployeeDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_employee
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") YmqEmployeeDao record, @Param("example") YmqEmployeeDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_employee
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    int updateByExample(@Param("record") YmqEmployeeDao record, @Param("example") YmqEmployeeDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_employee
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    int updateByPrimaryKeySelective(YmqEmployeeDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_employee
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(YmqEmployeeDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_employee
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    int updateByPrimaryKey(YmqEmployeeDao record);
}