package com.yumeiqi.dao;

import com.yumeiqi.domain.YmqOrderDetailDao;
import com.yumeiqi.domain.YmqOrderDetailDaoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface YmqOrderDetailDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order_detail
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    long countByExample(YmqOrderDetailDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order_detail
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int deleteByExample(YmqOrderDetailDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order_detail
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order_detail
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int insert(YmqOrderDetailDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order_detail
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int insertSelective(YmqOrderDetailDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order_detail
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    List<YmqOrderDetailDao> selectByExampleWithBLOBs(YmqOrderDetailDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order_detail
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    List<YmqOrderDetailDao> selectByExample(YmqOrderDetailDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order_detail
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    YmqOrderDetailDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order_detail
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") YmqOrderDetailDao record, @Param("example") YmqOrderDetailDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order_detail
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") YmqOrderDetailDao record, @Param("example") YmqOrderDetailDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order_detail
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByExample(@Param("record") YmqOrderDetailDao record, @Param("example") YmqOrderDetailDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order_detail
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByPrimaryKeySelective(YmqOrderDetailDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order_detail
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(YmqOrderDetailDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order_detail
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByPrimaryKey(YmqOrderDetailDao record);
}