package com.yumeiqi.dao;

import com.yumeiqi.domain.YmqOrderDao;
import com.yumeiqi.domain.YmqOrderDaoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YmqOrderDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    long countByExample(YmqOrderDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int deleteByExample(YmqOrderDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int deleteByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int insert(YmqOrderDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int insertSelective(YmqOrderDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    List<YmqOrderDao> selectByExampleWithBLOBs(YmqOrderDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    List<YmqOrderDao> selectByExample(YmqOrderDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    YmqOrderDao selectByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") YmqOrderDao record, @Param("example") YmqOrderDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") YmqOrderDao record, @Param("example") YmqOrderDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByExample(@Param("record") YmqOrderDao record, @Param("example") YmqOrderDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByPrimaryKeySelective(YmqOrderDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(YmqOrderDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_order
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByPrimaryKey(YmqOrderDao record);
}