package com.yumeiqi.dao;

import com.yumeiqi.domain.YmqRelationshipDao;
import com.yumeiqi.domain.YmqRelationshipDaoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface YmqRelationshipDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_relationship
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    long countByExample(YmqRelationshipDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_relationship
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int deleteByExample(YmqRelationshipDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_relationship
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int deleteByPrimaryKey(Integer relid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_relationship
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int insert(YmqRelationshipDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_relationship
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int insertSelective(YmqRelationshipDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_relationship
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    List<YmqRelationshipDao> selectByExampleWithBLOBs(YmqRelationshipDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_relationship
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    List<YmqRelationshipDao> selectByExample(YmqRelationshipDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_relationship
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    YmqRelationshipDao selectByPrimaryKey(Integer relid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_relationship
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") YmqRelationshipDao record, @Param("example") YmqRelationshipDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_relationship
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") YmqRelationshipDao record, @Param("example") YmqRelationshipDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_relationship
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByExample(@Param("record") YmqRelationshipDao record, @Param("example") YmqRelationshipDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_relationship
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByPrimaryKeySelective(YmqRelationshipDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_relationship
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(YmqRelationshipDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_relationship
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    int updateByPrimaryKey(YmqRelationshipDao record);
}