package com.yumeiqi.beans.vo;

public class YmqJobVo {

    private Integer jid;

    private String name;

    private Integer permissionId;

    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_job.jid
     *
     * @return the value of ymq_job.jid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getJid() {
        return jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_job.jid
     *
     * @param jid the value for ymq_job.jid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setJid(Integer jid) {
        this.jid = jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_job.name
     *
     * @return the value of ymq_job.name
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_job.name
     *
     * @param name the value for ymq_job.name
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_job.permission_id
     *
     * @return the value of ymq_job.permission_id
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_job.permission_id
     *
     * @param permissionId the value for ymq_job.permission_id
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_job.other
     *
     * @return the value of ymq_job.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_job.other
     *
     * @param other the value for ymq_job.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}