package com.yumeiqi.domain;

import java.util.Date;

public class YmqClientDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_client.cid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_client.name
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_client.phone
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_client.shop_name
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_client.province
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_client.city
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_client.county
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_client.join_date
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Date joinDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_client.isvip
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Integer isvip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_client.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_client.cid
     *
     * @return the value of ymq_client.cid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_client.cid
     *
     * @param cid the value for ymq_client.cid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_client.name
     *
     * @return the value of ymq_client.name
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_client.name
     *
     * @param name the value for ymq_client.name
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_client.phone
     *
     * @return the value of ymq_client.phone
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_client.phone
     *
     * @param phone the value for ymq_client.phone
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_client.shop_name
     *
     * @return the value of ymq_client.shop_name
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_client.shop_name
     *
     * @param shopName the value for ymq_client.shop_name
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_client.province
     *
     * @return the value of ymq_client.province
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_client.province
     *
     * @param province the value for ymq_client.province
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_client.city
     *
     * @return the value of ymq_client.city
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_client.city
     *
     * @param city the value for ymq_client.city
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_client.county
     *
     * @return the value of ymq_client.county
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_client.county
     *
     * @param county the value for ymq_client.county
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_client.join_date
     *
     * @return the value of ymq_client.join_date
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Date getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_client.join_date
     *
     * @param joinDate the value for ymq_client.join_date
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_client.isvip
     *
     * @return the value of ymq_client.isvip
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getIsvip() {
        return isvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_client.isvip
     *
     * @param isvip the value for ymq_client.isvip
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setIsvip(Integer isvip) {
        this.isvip = isvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_client.other
     *
     * @return the value of ymq_client.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_client.other
     *
     * @param other the value for ymq_client.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}