package com.yumeiqi.domain;

public class YmqDepartmentDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_department.did
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Integer did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_department.name
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_department.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_department.did
     *
     * @return the value of ymq_department.did
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_department.did
     *
     * @param did the value for ymq_department.did
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_department.name
     *
     * @return the value of ymq_department.name
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_department.name
     *
     * @param name the value for ymq_department.name
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_department.other
     *
     * @return the value of ymq_department.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_department.other
     *
     * @param other the value for ymq_department.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}