package com.yumeiqi.domain;

import java.math.BigDecimal;
import java.util.Date;

public class YmqEmployeeDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_employee.eid
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_employee.name
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_employee.age
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_employee.phone
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_employee.idcard
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_employee.jid
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    private Integer jid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_employee.jname
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    private String jname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_employee.salary
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    private BigDecimal salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_employee.push_money
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    private BigDecimal pushMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_employee.join_date
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    private Date joinDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_employee.status
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_employee.other
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_employee.eid
     *
     * @return the value of ymq_employee.eid
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_employee.eid
     *
     * @param eid the value for ymq_employee.eid
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_employee.name
     *
     * @return the value of ymq_employee.name
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_employee.name
     *
     * @param name the value for ymq_employee.name
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_employee.age
     *
     * @return the value of ymq_employee.age
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_employee.age
     *
     * @param age the value for ymq_employee.age
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_employee.phone
     *
     * @return the value of ymq_employee.phone
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_employee.phone
     *
     * @param phone the value for ymq_employee.phone
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_employee.idcard
     *
     * @return the value of ymq_employee.idcard
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_employee.idcard
     *
     * @param idcard the value for ymq_employee.idcard
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_employee.jid
     *
     * @return the value of ymq_employee.jid
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public Integer getJid() {
        return jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_employee.jid
     *
     * @param jid the value for ymq_employee.jid
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public void setJid(Integer jid) {
        this.jid = jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_employee.jname
     *
     * @return the value of ymq_employee.jname
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public String getJname() {
        return jname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_employee.jname
     *
     * @param jname the value for ymq_employee.jname
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public void setJname(String jname) {
        this.jname = jname == null ? null : jname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_employee.salary
     *
     * @return the value of ymq_employee.salary
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_employee.salary
     *
     * @param salary the value for ymq_employee.salary
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_employee.push_money
     *
     * @return the value of ymq_employee.push_money
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public BigDecimal getPushMoney() {
        return pushMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_employee.push_money
     *
     * @param pushMoney the value for ymq_employee.push_money
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public void setPushMoney(BigDecimal pushMoney) {
        this.pushMoney = pushMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_employee.join_date
     *
     * @return the value of ymq_employee.join_date
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public Date getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_employee.join_date
     *
     * @param joinDate the value for ymq_employee.join_date
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_employee.status
     *
     * @return the value of ymq_employee.status
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_employee.status
     *
     * @param status the value for ymq_employee.status
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_employee.other
     *
     * @return the value of ymq_employee.other
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_employee.other
     *
     * @param other the value for ymq_employee.other
     *
     * @mbg.generated Fri Jul 12 17:51:50 CST 2019
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}