package com.yumeiqi.domain;

import java.math.BigDecimal;

public class YmqGarmentDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_garment.gid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_garment.tid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_garment.clid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Integer clid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_garment.article_number
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String articleNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_garment.name
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_garment.color
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_garment.price
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_garment.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_garment.gid
     *
     * @return the value of ymq_garment.gid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_garment.gid
     *
     * @param gid the value for ymq_garment.gid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_garment.tid
     *
     * @return the value of ymq_garment.tid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_garment.tid
     *
     * @param tid the value for ymq_garment.tid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_garment.clid
     *
     * @return the value of ymq_garment.clid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getClid() {
        return clid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_garment.clid
     *
     * @param clid the value for ymq_garment.clid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setClid(Integer clid) {
        this.clid = clid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_garment.article_number
     *
     * @return the value of ymq_garment.article_number
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getArticleNumber() {
        return articleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_garment.article_number
     *
     * @param articleNumber the value for ymq_garment.article_number
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setArticleNumber(String articleNumber) {
        this.articleNumber = articleNumber == null ? null : articleNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_garment.name
     *
     * @return the value of ymq_garment.name
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_garment.name
     *
     * @param name the value for ymq_garment.name
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_garment.color
     *
     * @return the value of ymq_garment.color
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_garment.color
     *
     * @param color the value for ymq_garment.color
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_garment.price
     *
     * @return the value of ymq_garment.price
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_garment.price
     *
     * @param price the value for ymq_garment.price
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_garment.other
     *
     * @return the value of ymq_garment.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_garment.other
     *
     * @param other the value for ymq_garment.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}