package com.yumeiqi.domain;

import java.math.BigDecimal;

public class YmqOrderDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_order.oid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_order.order_number
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_order.cid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_order.total_money
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private BigDecimal totalMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_order.status
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_order.type
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_order.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_order.oid
     *
     * @return the value of ymq_order.oid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_order.oid
     *
     * @param oid the value for ymq_order.oid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_order.order_number
     *
     * @return the value of ymq_order.order_number
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_order.order_number
     *
     * @param orderNumber the value for ymq_order.order_number
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_order.cid
     *
     * @return the value of ymq_order.cid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_order.cid
     *
     * @param cid the value for ymq_order.cid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_order.total_money
     *
     * @return the value of ymq_order.total_money
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public BigDecimal getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_order.total_money
     *
     * @param totalMoney the value for ymq_order.total_money
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setTotalMoney(BigDecimal totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_order.status
     *
     * @return the value of ymq_order.status
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_order.status
     *
     * @param status the value for ymq_order.status
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_order.type
     *
     * @return the value of ymq_order.type
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_order.type
     *
     * @param type the value for ymq_order.type
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_order.other
     *
     * @return the value of ymq_order.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_order.other
     *
     * @param other the value for ymq_order.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}