package com.yumeiqi.domain;

public class YmqRelationshipDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_relationship.relid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Integer relid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_relationship.eid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_relationship.cid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_relationship.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_relationship.relid
     *
     * @return the value of ymq_relationship.relid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getRelid() {
        return relid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_relationship.relid
     *
     * @param relid the value for ymq_relationship.relid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setRelid(Integer relid) {
        this.relid = relid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_relationship.eid
     *
     * @return the value of ymq_relationship.eid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_relationship.eid
     *
     * @param eid the value for ymq_relationship.eid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_relationship.cid
     *
     * @return the value of ymq_relationship.cid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_relationship.cid
     *
     * @param cid the value for ymq_relationship.cid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_relationship.other
     *
     * @return the value of ymq_relationship.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_relationship.other
     *
     * @param other the value for ymq_relationship.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}