package com.yumeiqi.domain;

public class YmqRepositoryDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_repository.rid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_repository.gid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_repository.article_number
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String articleNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_repository.color
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_repository.number
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ymq_repository.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_repository.rid
     *
     * @return the value of ymq_repository.rid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_repository.rid
     *
     * @param rid the value for ymq_repository.rid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_repository.gid
     *
     * @return the value of ymq_repository.gid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_repository.gid
     *
     * @param gid the value for ymq_repository.gid
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_repository.article_number
     *
     * @return the value of ymq_repository.article_number
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getArticleNumber() {
        return articleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_repository.article_number
     *
     * @param articleNumber the value for ymq_repository.article_number
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setArticleNumber(String articleNumber) {
        this.articleNumber = articleNumber == null ? null : articleNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_repository.color
     *
     * @return the value of ymq_repository.color
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_repository.color
     *
     * @param color the value for ymq_repository.color
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_repository.number
     *
     * @return the value of ymq_repository.number
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_repository.number
     *
     * @param number the value for ymq_repository.number
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ymq_repository.other
     *
     * @return the value of ymq_repository.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ymq_repository.other
     *
     * @param other the value for ymq_repository.other
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}