package com.yumeiqi.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class YmqWageDaoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ymq_wage
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ymq_wage
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ymq_wage
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_wage
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public YmqWageDaoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_wage
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_wage
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_wage
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_wage
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_wage
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_wage
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_wage
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_wage
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_wage
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ymq_wage
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ymq_wage
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWidIsNull() {
            addCriterion("wid is null");
            return (Criteria) this;
        }

        public Criteria andWidIsNotNull() {
            addCriterion("wid is not null");
            return (Criteria) this;
        }

        public Criteria andWidEqualTo(Integer value) {
            addCriterion("wid =", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidNotEqualTo(Integer value) {
            addCriterion("wid <>", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidGreaterThan(Integer value) {
            addCriterion("wid >", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidGreaterThanOrEqualTo(Integer value) {
            addCriterion("wid >=", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidLessThan(Integer value) {
            addCriterion("wid <", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidLessThanOrEqualTo(Integer value) {
            addCriterion("wid <=", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidIn(List<Integer> values) {
            addCriterion("wid in", values, "wid");
            return (Criteria) this;
        }

        public Criteria andWidNotIn(List<Integer> values) {
            addCriterion("wid not in", values, "wid");
            return (Criteria) this;
        }

        public Criteria andWidBetween(Integer value1, Integer value2) {
            addCriterion("wid between", value1, value2, "wid");
            return (Criteria) this;
        }

        public Criteria andWidNotBetween(Integer value1, Integer value2) {
            addCriterion("wid not between", value1, value2, "wid");
            return (Criteria) this;
        }

        public Criteria andEidIsNull() {
            addCriterion("eid is null");
            return (Criteria) this;
        }

        public Criteria andEidIsNotNull() {
            addCriterion("eid is not null");
            return (Criteria) this;
        }

        public Criteria andEidEqualTo(Integer value) {
            addCriterion("eid =", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotEqualTo(Integer value) {
            addCriterion("eid <>", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThan(Integer value) {
            addCriterion("eid >", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThanOrEqualTo(Integer value) {
            addCriterion("eid >=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThan(Integer value) {
            addCriterion("eid <", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThanOrEqualTo(Integer value) {
            addCriterion("eid <=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidIn(List<Integer> values) {
            addCriterion("eid in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotIn(List<Integer> values) {
            addCriterion("eid not in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidBetween(Integer value1, Integer value2) {
            addCriterion("eid between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotBetween(Integer value1, Integer value2) {
            addCriterion("eid not between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andEnameIsNull() {
            addCriterion("ename is null");
            return (Criteria) this;
        }

        public Criteria andEnameIsNotNull() {
            addCriterion("ename is not null");
            return (Criteria) this;
        }

        public Criteria andEnameEqualTo(String value) {
            addCriterion("ename =", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotEqualTo(String value) {
            addCriterion("ename <>", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameGreaterThan(String value) {
            addCriterion("ename >", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameGreaterThanOrEqualTo(String value) {
            addCriterion("ename >=", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLessThan(String value) {
            addCriterion("ename <", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLessThanOrEqualTo(String value) {
            addCriterion("ename <=", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLike(String value) {
            addCriterion("ename like", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotLike(String value) {
            addCriterion("ename not like", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameIn(List<String> values) {
            addCriterion("ename in", values, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotIn(List<String> values) {
            addCriterion("ename not in", values, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameBetween(String value1, String value2) {
            addCriterion("ename between", value1, value2, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotBetween(String value1, String value2) {
            addCriterion("ename not between", value1, value2, "ename");
            return (Criteria) this;
        }

        public Criteria andSalaryIsNull() {
            addCriterion("salary is null");
            return (Criteria) this;
        }

        public Criteria andSalaryIsNotNull() {
            addCriterion("salary is not null");
            return (Criteria) this;
        }

        public Criteria andSalaryEqualTo(BigDecimal value) {
            addCriterion("salary =", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryNotEqualTo(BigDecimal value) {
            addCriterion("salary <>", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryGreaterThan(BigDecimal value) {
            addCriterion("salary >", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("salary >=", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryLessThan(BigDecimal value) {
            addCriterion("salary <", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryLessThanOrEqualTo(BigDecimal value) {
            addCriterion("salary <=", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryIn(List<BigDecimal> values) {
            addCriterion("salary in", values, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryNotIn(List<BigDecimal> values) {
            addCriterion("salary not in", values, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("salary between", value1, value2, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("salary not between", value1, value2, "salary");
            return (Criteria) this;
        }

        public Criteria andPushMoneyIsNull() {
            addCriterion("push_money is null");
            return (Criteria) this;
        }

        public Criteria andPushMoneyIsNotNull() {
            addCriterion("push_money is not null");
            return (Criteria) this;
        }

        public Criteria andPushMoneyEqualTo(BigDecimal value) {
            addCriterion("push_money =", value, "pushMoney");
            return (Criteria) this;
        }

        public Criteria andPushMoneyNotEqualTo(BigDecimal value) {
            addCriterion("push_money <>", value, "pushMoney");
            return (Criteria) this;
        }

        public Criteria andPushMoneyGreaterThan(BigDecimal value) {
            addCriterion("push_money >", value, "pushMoney");
            return (Criteria) this;
        }

        public Criteria andPushMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("push_money >=", value, "pushMoney");
            return (Criteria) this;
        }

        public Criteria andPushMoneyLessThan(BigDecimal value) {
            addCriterion("push_money <", value, "pushMoney");
            return (Criteria) this;
        }

        public Criteria andPushMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("push_money <=", value, "pushMoney");
            return (Criteria) this;
        }

        public Criteria andPushMoneyIn(List<BigDecimal> values) {
            addCriterion("push_money in", values, "pushMoney");
            return (Criteria) this;
        }

        public Criteria andPushMoneyNotIn(List<BigDecimal> values) {
            addCriterion("push_money not in", values, "pushMoney");
            return (Criteria) this;
        }

        public Criteria andPushMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("push_money between", value1, value2, "pushMoney");
            return (Criteria) this;
        }

        public Criteria andPushMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("push_money not between", value1, value2, "pushMoney");
            return (Criteria) this;
        }

        public Criteria andLeaveIsNull() {
            addCriterion("leave is null");
            return (Criteria) this;
        }

        public Criteria andLeaveIsNotNull() {
            addCriterion("leave is not null");
            return (Criteria) this;
        }

        public Criteria andLeaveEqualTo(BigDecimal value) {
            addCriterion("leave =", value, "leave");
            return (Criteria) this;
        }

        public Criteria andLeaveNotEqualTo(BigDecimal value) {
            addCriterion("leave <>", value, "leave");
            return (Criteria) this;
        }

        public Criteria andLeaveGreaterThan(BigDecimal value) {
            addCriterion("leave >", value, "leave");
            return (Criteria) this;
        }

        public Criteria andLeaveGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("leave >=", value, "leave");
            return (Criteria) this;
        }

        public Criteria andLeaveLessThan(BigDecimal value) {
            addCriterion("leave <", value, "leave");
            return (Criteria) this;
        }

        public Criteria andLeaveLessThanOrEqualTo(BigDecimal value) {
            addCriterion("leave <=", value, "leave");
            return (Criteria) this;
        }

        public Criteria andLeaveIn(List<BigDecimal> values) {
            addCriterion("leave in", values, "leave");
            return (Criteria) this;
        }

        public Criteria andLeaveNotIn(List<BigDecimal> values) {
            addCriterion("leave not in", values, "leave");
            return (Criteria) this;
        }

        public Criteria andLeaveBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("leave between", value1, value2, "leave");
            return (Criteria) this;
        }

        public Criteria andLeaveNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("leave not between", value1, value2, "leave");
            return (Criteria) this;
        }

        public Criteria andAllTheWorkIsNull() {
            addCriterion("all_the_work is null");
            return (Criteria) this;
        }

        public Criteria andAllTheWorkIsNotNull() {
            addCriterion("all_the_work is not null");
            return (Criteria) this;
        }

        public Criteria andAllTheWorkEqualTo(BigDecimal value) {
            addCriterion("all_the_work =", value, "allTheWork");
            return (Criteria) this;
        }

        public Criteria andAllTheWorkNotEqualTo(BigDecimal value) {
            addCriterion("all_the_work <>", value, "allTheWork");
            return (Criteria) this;
        }

        public Criteria andAllTheWorkGreaterThan(BigDecimal value) {
            addCriterion("all_the_work >", value, "allTheWork");
            return (Criteria) this;
        }

        public Criteria andAllTheWorkGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("all_the_work >=", value, "allTheWork");
            return (Criteria) this;
        }

        public Criteria andAllTheWorkLessThan(BigDecimal value) {
            addCriterion("all_the_work <", value, "allTheWork");
            return (Criteria) this;
        }

        public Criteria andAllTheWorkLessThanOrEqualTo(BigDecimal value) {
            addCriterion("all_the_work <=", value, "allTheWork");
            return (Criteria) this;
        }

        public Criteria andAllTheWorkIn(List<BigDecimal> values) {
            addCriterion("all_the_work in", values, "allTheWork");
            return (Criteria) this;
        }

        public Criteria andAllTheWorkNotIn(List<BigDecimal> values) {
            addCriterion("all_the_work not in", values, "allTheWork");
            return (Criteria) this;
        }

        public Criteria andAllTheWorkBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("all_the_work between", value1, value2, "allTheWork");
            return (Criteria) this;
        }

        public Criteria andAllTheWorkNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("all_the_work not between", value1, value2, "allTheWork");
            return (Criteria) this;
        }

        public Criteria andBonusIsNull() {
            addCriterion("bonus is null");
            return (Criteria) this;
        }

        public Criteria andBonusIsNotNull() {
            addCriterion("bonus is not null");
            return (Criteria) this;
        }

        public Criteria andBonusEqualTo(BigDecimal value) {
            addCriterion("bonus =", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusNotEqualTo(BigDecimal value) {
            addCriterion("bonus <>", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusGreaterThan(BigDecimal value) {
            addCriterion("bonus >", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bonus >=", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusLessThan(BigDecimal value) {
            addCriterion("bonus <", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bonus <=", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusIn(List<BigDecimal> values) {
            addCriterion("bonus in", values, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusNotIn(List<BigDecimal> values) {
            addCriterion("bonus not in", values, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bonus between", value1, value2, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bonus not between", value1, value2, "bonus");
            return (Criteria) this;
        }

        public Criteria andPenaltyIsNull() {
            addCriterion("penalty is null");
            return (Criteria) this;
        }

        public Criteria andPenaltyIsNotNull() {
            addCriterion("penalty is not null");
            return (Criteria) this;
        }

        public Criteria andPenaltyEqualTo(BigDecimal value) {
            addCriterion("penalty =", value, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyNotEqualTo(BigDecimal value) {
            addCriterion("penalty <>", value, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyGreaterThan(BigDecimal value) {
            addCriterion("penalty >", value, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("penalty >=", value, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyLessThan(BigDecimal value) {
            addCriterion("penalty <", value, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("penalty <=", value, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyIn(List<BigDecimal> values) {
            addCriterion("penalty in", values, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyNotIn(List<BigDecimal> values) {
            addCriterion("penalty not in", values, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("penalty between", value1, value2, "penalty");
            return (Criteria) this;
        }

        public Criteria andPenaltyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("penalty not between", value1, value2, "penalty");
            return (Criteria) this;
        }

        public Criteria andAbsenteeismIsNull() {
            addCriterion("absenteeism is null");
            return (Criteria) this;
        }

        public Criteria andAbsenteeismIsNotNull() {
            addCriterion("absenteeism is not null");
            return (Criteria) this;
        }

        public Criteria andAbsenteeismEqualTo(BigDecimal value) {
            addCriterion("absenteeism =", value, "absenteeism");
            return (Criteria) this;
        }

        public Criteria andAbsenteeismNotEqualTo(BigDecimal value) {
            addCriterion("absenteeism <>", value, "absenteeism");
            return (Criteria) this;
        }

        public Criteria andAbsenteeismGreaterThan(BigDecimal value) {
            addCriterion("absenteeism >", value, "absenteeism");
            return (Criteria) this;
        }

        public Criteria andAbsenteeismGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("absenteeism >=", value, "absenteeism");
            return (Criteria) this;
        }

        public Criteria andAbsenteeismLessThan(BigDecimal value) {
            addCriterion("absenteeism <", value, "absenteeism");
            return (Criteria) this;
        }

        public Criteria andAbsenteeismLessThanOrEqualTo(BigDecimal value) {
            addCriterion("absenteeism <=", value, "absenteeism");
            return (Criteria) this;
        }

        public Criteria andAbsenteeismIn(List<BigDecimal> values) {
            addCriterion("absenteeism in", values, "absenteeism");
            return (Criteria) this;
        }

        public Criteria andAbsenteeismNotIn(List<BigDecimal> values) {
            addCriterion("absenteeism not in", values, "absenteeism");
            return (Criteria) this;
        }

        public Criteria andAbsenteeismBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("absenteeism between", value1, value2, "absenteeism");
            return (Criteria) this;
        }

        public Criteria andAbsenteeismNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("absenteeism not between", value1, value2, "absenteeism");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyIsNull() {
            addCriterion("leave_early is null");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyIsNotNull() {
            addCriterion("leave_early is not null");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyEqualTo(BigDecimal value) {
            addCriterion("leave_early =", value, "leaveEarly");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyNotEqualTo(BigDecimal value) {
            addCriterion("leave_early <>", value, "leaveEarly");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyGreaterThan(BigDecimal value) {
            addCriterion("leave_early >", value, "leaveEarly");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("leave_early >=", value, "leaveEarly");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyLessThan(BigDecimal value) {
            addCriterion("leave_early <", value, "leaveEarly");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("leave_early <=", value, "leaveEarly");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyIn(List<BigDecimal> values) {
            addCriterion("leave_early in", values, "leaveEarly");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyNotIn(List<BigDecimal> values) {
            addCriterion("leave_early not in", values, "leaveEarly");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("leave_early between", value1, value2, "leaveEarly");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("leave_early not between", value1, value2, "leaveEarly");
            return (Criteria) this;
        }

        public Criteria andFsalaryIsNull() {
            addCriterion("fsalary is null");
            return (Criteria) this;
        }

        public Criteria andFsalaryIsNotNull() {
            addCriterion("fsalary is not null");
            return (Criteria) this;
        }

        public Criteria andFsalaryEqualTo(BigDecimal value) {
            addCriterion("fsalary =", value, "fsalary");
            return (Criteria) this;
        }

        public Criteria andFsalaryNotEqualTo(BigDecimal value) {
            addCriterion("fsalary <>", value, "fsalary");
            return (Criteria) this;
        }

        public Criteria andFsalaryGreaterThan(BigDecimal value) {
            addCriterion("fsalary >", value, "fsalary");
            return (Criteria) this;
        }

        public Criteria andFsalaryGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fsalary >=", value, "fsalary");
            return (Criteria) this;
        }

        public Criteria andFsalaryLessThan(BigDecimal value) {
            addCriterion("fsalary <", value, "fsalary");
            return (Criteria) this;
        }

        public Criteria andFsalaryLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fsalary <=", value, "fsalary");
            return (Criteria) this;
        }

        public Criteria andFsalaryIn(List<BigDecimal> values) {
            addCriterion("fsalary in", values, "fsalary");
            return (Criteria) this;
        }

        public Criteria andFsalaryNotIn(List<BigDecimal> values) {
            addCriterion("fsalary not in", values, "fsalary");
            return (Criteria) this;
        }

        public Criteria andFsalaryBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fsalary between", value1, value2, "fsalary");
            return (Criteria) this;
        }

        public Criteria andFsalaryNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fsalary not between", value1, value2, "fsalary");
            return (Criteria) this;
        }

        public Criteria andWdateIsNull() {
            addCriterion("wdate is null");
            return (Criteria) this;
        }

        public Criteria andWdateIsNotNull() {
            addCriterion("wdate is not null");
            return (Criteria) this;
        }

        public Criteria andWdateEqualTo(Date value) {
            addCriterion("wdate =", value, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateNotEqualTo(Date value) {
            addCriterion("wdate <>", value, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateGreaterThan(Date value) {
            addCriterion("wdate >", value, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateGreaterThanOrEqualTo(Date value) {
            addCriterion("wdate >=", value, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateLessThan(Date value) {
            addCriterion("wdate <", value, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateLessThanOrEqualTo(Date value) {
            addCriterion("wdate <=", value, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateIn(List<Date> values) {
            addCriterion("wdate in", values, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateNotIn(List<Date> values) {
            addCriterion("wdate not in", values, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateBetween(Date value1, Date value2) {
            addCriterion("wdate between", value1, value2, "wdate");
            return (Criteria) this;
        }

        public Criteria andWdateNotBetween(Date value1, Date value2) {
            addCriterion("wdate not between", value1, value2, "wdate");
            return (Criteria) this;
        }

        public Criteria andVerifierIsNull() {
            addCriterion("verifier is null");
            return (Criteria) this;
        }

        public Criteria andVerifierIsNotNull() {
            addCriterion("verifier is not null");
            return (Criteria) this;
        }

        public Criteria andVerifierEqualTo(Integer value) {
            addCriterion("verifier =", value, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierNotEqualTo(Integer value) {
            addCriterion("verifier <>", value, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierGreaterThan(Integer value) {
            addCriterion("verifier >", value, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierGreaterThanOrEqualTo(Integer value) {
            addCriterion("verifier >=", value, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierLessThan(Integer value) {
            addCriterion("verifier <", value, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierLessThanOrEqualTo(Integer value) {
            addCriterion("verifier <=", value, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierIn(List<Integer> values) {
            addCriterion("verifier in", values, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierNotIn(List<Integer> values) {
            addCriterion("verifier not in", values, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierBetween(Integer value1, Integer value2) {
            addCriterion("verifier between", value1, value2, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierNotBetween(Integer value1, Integer value2) {
            addCriterion("verifier not between", value1, value2, "verifier");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ymq_wage
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 12 16:19:15 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ymq_wage
     *
     * @mbg.generated Fri Jul 12 16:19:15 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}